"""init_db

Revision ID: edc9c8ff1171
Revises: 
Create Date: 2026-02-27 21:56:57.684235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc9c8ff1171'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pest_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('DISEASE', 'PEST', name='pestcategoryenum'), nullable=False),
    sa.Column('affected_part', sa.String(length=100), nullable=True),
    sa.Column('symptom_description', sa.Text(), nullable=True),
    sa.Column('peak_season', sa.String(length=100), nullable=True),
    sa.Column('typical_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pest_info_id'), 'pest_info', ['id'], unique=False)
    op.create_index(op.f('ix_pest_info_name'), 'pest_info', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'EXPERT', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=False, comment='0-未激活, 1-已激活'),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='register, reset_password'),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_email'), 'verification_codes', ['email'], unique=False)
    op.create_index(op.f('ix_verification_codes_id'), 'verification_codes', ['id'], unique=False)
    op.create_table('warning_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('NORMAL', 'URGENT', name='warninglevelenum'), nullable=False),
    sa.Column('affected_scope', sa.String(length=255), nullable=False),
    sa.Column('prevention_measures', sa.Text(), nullable=False),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warning_messages_id'), 'warning_messages', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', name='contentstatusenum'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('audit_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('governance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pest_type', sa.String(length=100), nullable=False),
    sa.Column('found_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='governancestatusenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_records_id'), 'governance_records', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', name='contentstatusenum'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('prevention_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pest_id', sa.Integer(), nullable=False),
    sa.Column('pesticide_name', sa.String(length=100), nullable=False),
    sa.Column('recommended_dosage', sa.String(length=100), nullable=True),
    sa.Column('application_time', sa.String(length=100), nullable=True),
    sa.Column('operation_spec', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pest_id'], ['pest_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prevention_schemes_id'), 'prevention_schemes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prevention_schemes_id'), table_name='prevention_schemes')
    op.drop_table('prevention_schemes')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_governance_records_id'), table_name='governance_records')
    op.drop_table('governance_records')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_warning_messages_id'), table_name='warning_messages')
    op.drop_table('warning_messages')
    op.drop_index(op.f('ix_verification_codes_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_email'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pest_info_name'), table_name='pest_info')
    op.drop_index(op.f('ix_pest_info_id'), table_name='pest_info')
    op.drop_table('pest_info')
    # ### end Alembic commands ###
